<?php
/**
 * AddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * AddressTest Class Doc Comment
 *
 * @category    Class
 * @description Address
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Address"
     */
    public function testAddress()
    {
    }

    /**
     * Test attribute "house_number"
     */
    public function testPropertyHouseNumber()
    {
    }

    /**
     * Test attribute "road"
     */
    public function testPropertyRoad()
    {
    }

    /**
     * Test attribute "residential"
     */
    public function testPropertyResidential()
    {
    }

    /**
     * Test attribute "borough"
     */
    public function testPropertyBorough()
    {
    }

    /**
     * Test attribute "neighbourhood"
     */
    public function testPropertyNeighbourhood()
    {
    }

    /**
     * Test attribute "quarter"
     */
    public function testPropertyQuarter()
    {
    }

    /**
     * Test attribute "hamlet"
     */
    public function testPropertyHamlet()
    {
    }

    /**
     * Test attribute "suburb"
     */
    public function testPropertySuburb()
    {
    }

    /**
     * Test attribute "island"
     */
    public function testPropertyIsland()
    {
    }

    /**
     * Test attribute "village"
     */
    public function testPropertyVillage()
    {
    }

    /**
     * Test attribute "town"
     */
    public function testPropertyTown()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "city_district"
     */
    public function testPropertyCityDistrict()
    {
    }

    /**
     * Test attribute "county"
     */
    public function testPropertyCounty()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "state_district"
     */
    public function testPropertyStateDistrict()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "state_code"
     */
    public function testPropertyStateCode()
    {
    }
}
