<?php
/**
 * DirectionsDirectionsRoutesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LocationIQ
 *
 * LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * DirectionsDirectionsRoutesTest Class Doc Comment
 *
 * @category    Class
 * @description DirectionsDirectionsRoutes
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DirectionsDirectionsRoutesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DirectionsDirectionsRoutes"
     */
    public function testDirectionsDirectionsRoutes()
    {
    }

    /**
     * Test attribute "legs"
     */
    public function testPropertyLegs()
    {
    }

    /**
     * Test attribute "weight_name"
     */
    public function testPropertyWeightName()
    {
    }

    /**
     * Test attribute "geometry"
     */
    public function testPropertyGeometry()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }
}
